- name: Installs packages
  apt:
    name: [
      'htop',
      'tmux',
      'vim-runtime',
      'vim-common',
      'vim-tiny',
      'vim-nox',
      'i3',
      'i3-wm',
      'i3lock',
      'i3status',
      'fish',
      'fish-common',
      'wget',
      'curl',
      'git',
      'network-manager-gnome',
      'dunst',
      'terminator',
    ]

- name: Installs terraform
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    sudo apt-get update
    sudo apt-get install -y terraform
  args:
    warn: false
